[package]
name = "ffi_test"
version = "0.1.0"
authors = ["Marco Napetti <marco.napetti@gmail.com>"]

[dependencies]
dynamic_reload = "0.3.0"
toml = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
