[package]
name = "test_lib"
version = "0.1.0"
authors = ["Marco Napetti <marco.napetti@gmail.com>"]

[lib]
name = "test_lib"
crate-type = ["dylib"]

[dependencies]
toml = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
